language: cpp
sudo: required
dist: trusty
compiler:
    - clang
    - gcc
before_install:
    - pip install --user cpp-coveralls
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - echo "yes" | sudo add-apt-repository 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.9 main'
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    - sudo apt-get -qq update
    - sudo apt-get install -y g++-6 clang-3.9 libgfortran-6-dev libgcc-6-dev libiomp-dev doxygen python-dev python-instant libeigen3-dev libopenblas-dev gfortran
    - sudo apt-get install -y lcov curl
    - wget -O boost_1_61_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.gz/download
    - tar xfz boost_1_61_0.tar.gz
    - cd boost_1_61_0/
    - ./bootstrap.sh --prefix=/usr/local
    - echo 'using mpi : : <find-shared-library>mpic++ ;' >> project-config.jam
    - cat project-config.jam
    - sudo ./b2 --with-mpi --with-serialization -d0 -q install
    - cd ..
before_script:
    - mkdir build
    - cd build
    - if [[ "$CXX" == "g++" ]]; then CXX=g++-6 cmake -DBOOST_ROOT=/usr/local -DBoost_NO_SYSTEM_PATHS=TRUE -DBoost_NO_BOOST_CMAKE=TRUE ..; fi
    - if [[ "$CXX" == "clang++" ]]; then CXX=clang++-3.9 cmake -DBOOST_ROOT=/usr/local -DBoost_NO_SYSTEM_PATHS=TRUE -DBoost_NO_BOOST_CMAKE=TRUE ..; fi
script:
    - make -j2
    - ctest -V
after_success:
    - cd ..
    - if [[ "$CXX" =~ ^g.* ]]; then coveralls --gcov-options '\-lp'; fi
